spring:
#  redis:
#    host: 110.42.165.13
#    password:
#    port: 7379

  datasource:
    url: jdbc:mysql://110.42.165.13:3306/music_base?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: music
    password: music_base
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 500
    max-idle: 150
    min-idle: 30
    initial-size: 10
    max-wait: 60000
    validation-query: select 1
    test-while-idle: true
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 600000

  thymeleaf:
    prefix: classpath:/templates
mybatis:
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8901